project:
  type: book

book:
  title: "Multivariate Analysis with Optimal Scaling"
  author: "Jan de Leeuw"
  date: "7/22/2026"
  chapters:
    - index.qmd
    - preface.qmd
    - intro.qmd
    - coding.qmd
    - algorithm.qmd
    - homals.qmd
    - corals.qmd
    - coranals.qmd
    - princals.qmd
    - canals.qmd
    - morals.qmd
    - criminals.qmd
#    - overals.qmd
    - references.qmd

bibliography: 
    - total.bib 
    - mypubs.bib
    
fontsize: 12pt
pdf-engine: lualatex
keep-tex: true
mainfont: Times New Roman

format:
  pdf:
    documentclass: scrreprt
    include-in-header: 
     - preamble.tex

